application: sayyesassistant
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# prod and final routes
- url: /session/.*
  script: session.application

- url: /css-min
  static_dir: static/css-min/

- url: /js-min
  static_dir: static/js-min

- url: /img
  static_dir: static/img

# dev and tests routes
- url: /examples
  static_dir: static/examples

- url: /tests
  static_dir: static/tests

- url: /bower_path
  static_dir: bower_components

- url: /js-src
  static_dir: static/js

- url: /guideline
  static_files: static/index.html
  upload: static/index.html

- url: /mock-service/.*
  script: mock-service.application

- url: /mock-data/
  static_dir: static/mock

# all url fallbacks goes here
- url: /.*
  script: website.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
