application: sayyesassistant
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css-min
  static_dir: static/css-min/

- url: /js-min
  static_dir: static/js-min

- url: /img
  static_dir: static/img

- url: /tests
  static_dir: static/tests

- url: /guideline
  static_files: static/index.html
  upload: static/index.html

- url: /mock-service/.*
  script: mock-service.application

- url: /mock-data/
  static_dir: static/mock

- url: /session/.*
  script: session.application

- url: /.*
  script: website.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
