application: sayyesassistant
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img

- url: /session/.*
  script: session.application
- url: /.*
  script: website.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
