application: sayyesassistant
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# prod and final routes
- url: /session/.*
  script: session.application

- url: /css-min/(.*\.css)
  mime_type: text/css
  static_files: static/css-min/\1
  upload: static/css-min/(.*\.css)

- url: /js-min/(.*\.js.*)
  mime_type: text/javascript
  static_files: static/js-min/\1
  upload: static/js-min/(.*\.js.*)

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))

# dev and tests routes
- url: /examples/(.*\.html)
  mime_type: text/html
  static_files: static/examples/\1
  upload: static/examples/(.*\.html)

- url: /tests
  static_dir: static/tests

- url: /bower_path
  static_dir: bower_components

- url: /js-src
  static_dir: static/js
  
- url: /flat-ui
  static_dir: static/flat-ui

- url: /static
  mime_type: text/markdown
  static_files: static/README.md
  upload: static/README.md

- url: /mock-service/.*
  script: mock-service.application

- url: /mock-data/
  static_dir: static/mock

# all url fallbacks goes here
- url: /.*
  script: website.application

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
